### ISSUE TITLE
Example deployed

### ISSUE THREAD

**Issue by Theorycrafting** [Judaxx/osrs-json-api#1]
It would be fantastic if there was an example URL of a deployed app using this JSON.
Perhaps a simple vanilla codesandbox and in the javascript file using `osrs-json-api` and console logging that JSON response would be fantastic!

You have it very well documented, but when I went to use it, I was having troubles with getting errors. I think with CORS which I would normally prefix any endpoint with `https://cors-anywhere.herokuapp.com/`

If you want to talk about this otherwise, we could on disc or in game 👍 
Rsn: Bag

**Comment by Judaxx** [comment]
Hey there,

I'm not exactly sure I follow what you're asking, but you might have to enable CORS on your node server for better results. 

Feel free to add me on discord (Parker#8782) and I can send you an example of one of my projects using this library.
