### ISSUE TITLE
Error Handling not working properly?

### ISSUE THREAD

**Issue by Icekraks** [Judaxx/osrs-json-api#22]
![image](https://user-images.githubusercontent.com/5193466/107918488-dbad4580-6fbd-11eb-9ed3-a448649c496d.png)
![image](https://user-images.githubusercontent.com/5193466/107918513-ea93f800-6fbd-11eb-8fbe-11cadc03a1b4.png)
Screenshots of where the error is being thrown and the console printout

Code Snippet that calls upon the JSON API
```
import {hiscores} from 'osrs-json-api';

displayStats = async() =>{
    let stats = await hiscores.getPlayer('IcekraksIG');
    console.log(stats);
}
```

**Comment by Judaxx** [comment]
Hey,

Sorry for the late response, but ideally you should be using this package in the server side to avoid this problem with CORS that most modern browsers now block. 

If you still want to make http requests from other sources (outside localhost or your domain) you have to explicitly allow CORS on your react app.

This is not an issue with the package, but with how browsers and HTTP works. I'll close for now, but feel free to reach out to me if you still have questions.
